//
import Head from "next/head";
import Link from "next/link";
//
import { clsx } from "clsx";
export const MainLayout: React.FCC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={clsx(
          "grid h-screen w-screen grid-rows-[60px,1fr]",
          "sm:grid-cols-[80px,1fr]"
        )}
      >
        <aside className="row-span-2 bg-blue-400">
          <ul>
            {items.map(({ key, href, label }) => (
              <li key={key}>
                <Link href={href}>
                  <div className="aspect-square hover:bg-green-400">
                    <div className="flex h-full w-full items-center justify-center">
                      {label}
                    </div>
                  </div>
                </Link>
              </li>
            ))}
          </ul>
        </aside>
        <header className="bg-red-400"></header>
        <main className="overflow-y-auto">{children}</main>
      </div>
    </>
  );
};
const items = [
  {
    key: "home",
    href: "/",
    label: "Home",
  },
  {
    key: "about",
    href: "/about",
    label: "About",
  },
];
